# Generated by Django 6.0.1 on 2026-01-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmentsurveillance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_capteur', models.CharField(max_length=50)),
                ('valeur', models.FloatField()),
                ('date_lecture', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
