# Generated by Django 6.0.1 on 2026-01-10 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmentsurveillance', '0002_capteur_delete_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('TEMP', 'Température Élevée'), ('HUM', 'Humidité Critique'), ('BATT', 'Batterie Faible')], max_length=10)),
                ('value_triggered', models.FloatField(verbose_name='Valeur relevée')),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerte',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_eui', models.CharField(max_length=16, unique=True, verbose_name='Identifiant LoRa (EUI)')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'appareil")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Appareil',
                'verbose_name_plural': 'Appareils',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Température (°C)')),
                ('humidity', models.FloatField(verbose_name='Humidité (%)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetries', to='environmentsurveillance.device')),
            ],
            options={
                'verbose_name': 'Donnée Environnementale',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='environmentsurveillance.device')),
            ],
            options={
                'verbose_name': 'Donnée GPS',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Capteur',
        ),
        migrations.AddField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environmentsurveillance.device'),
        ),
    ]
