# Generated by Django 6.0.1 on 2026-01-11 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmentsurveillance', '0003_alert_device_environmentaldata_gpsdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentaldata',
            name='device',
        ),
        migrations.RemoveField(
            model_name='gpsdata',
            name='device',
        ),
        migrations.CreateModel(
            name='TTNUplink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=128)),
                ('raw_payload', models.JSONField()),
                ('decoded_payload', models.JSONField(blank=True, null=True)),
                ('rssi', models.FloatField(blank=True, null=True)),
                ('snr', models.FloatField(blank=True, null=True)),
                ('f_port', models.IntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttn_uplinks', to='environmentsurveillance.device')),
            ],
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='EnvironmentalData',
        ),
        migrations.DeleteModel(
            name='GPSData',
        ),
    ]
