# Generated by Django 6.0.1 on 2026-02-05 21:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmentsurveillance', '0005_telemetrypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrypoint',
            name='snr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetrypoint',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='environmentsurveillance.device'),
        ),
        migrations.AlterField(
            model_name='telemetrypoint',
            name='ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
